name: 'Download and Setup Cached Anchor CLI'
description: 'Downloads and sets up the Anchor CLI from a public repository, using GITHUB_TOKEN to avoid rate limiting'
inputs:
  rev:
    description: 'Anchor revision to download'
    required: false
  version:
    description: 'Anchor version to download'
    required: false
    default: '0.30.1'
  target:
    description: 'Build target'
    required: false
    default: 'x86_64-unknown-linux-musl'
runs:
  using: "composite"
  steps:
    - name: Set version or rev
      id: set_version
      shell: bash
      run: |
        if [ -n "${{ inputs.rev }}" ]; then
          echo "version_or_rev=${{ inputs.rev }}" >> $GITHUB_OUTPUT
        elif [ -n "${{ inputs.version }}" ]; then
          echo "version_or_rev=${{ inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "version_or_rev=0.30.1" >> $GITHUB_OUTPUT
        fi

    - name: Download and setup Anchor CLI binary
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        mkdir -p /home/runner/.local/bin
        DOWNLOAD_URL="https://github.com/debridge-finance/anchor-build/releases/download/anchor-${{ steps.set_version.outputs.version_or_rev }}/anchor-${{ inputs.target }}"
        
        HTTP_STATUS=$(curl -L -w "%{http_code}" -H "Authorization: token $GITHUB_TOKEN" -o /home/runner/.local/bin/anchor $DOWNLOAD_URL)
        if [ $HTTP_STATUS -eq 200 ]; then
          chmod +x /home/runner/.local/bin/anchor
        else
          echo "Error: Failed to download Anchor CLI. HTTP Status: $HTTP_STATUS"
          exit 1
        fi

    - name: Add Anchor CLI to PATH
      shell: bash
      run: echo "/home/runner/.local/bin" >> $GITHUB_PATH

    - name: Verify Anchor CLI installation
      shell: bash
      run: anchor --version